# Generated by Django 3.0.8 on 2020-08-01 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_todoitem_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='update',
            new_name='updated',
        ),
    ]
